redmine_cua/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/cua', 		 :to => 'cua_project_dependencies#indexall'
get '/cua_security', :to => 'cua_project_security_issues#indexall'

scope 'projects/:project_id' do
  get 'cua',         		to: 'cua_project_dependencies#index'
  get 'cua_security',       to: 'cua_project_security_issues#index'

  put 'cua_settings/save'

end

redmine_cua/app/models/cua_dependencies.rb
class CuaDependencies < ActiveRecord::Base
  unloadable
  
  belongs_to :project

  scope :by_project, lambda {|project| where("project_id = ?", project.id)}


  def do_update
  	return self.state == 'update'
  end

  def do_remove
  	return self.state == 'remove'
  end

end

redmine_cua/app/models/cua_security_issues.rb
class CuaSecurityIssues < ActiveRecord::Base
  unloadable
  
  belongs_to :project

  scope :by_project, lambda {|project| where("project_id = ?", project.id)}


  def do_secure
  	return self.state == 'open'
  end

end

redmine_cua/app/models/cua_setting.rb
class CuaSetting < ActiveRecord::Base
  unloadable

  ## Relations
  belongs_to :project

  attr_accessible :lock_path, :check_update, :check_security, :php_bin

  ## Validations
  validates :project_id, presence: true, uniqueness: true
  #validates :url,        presence: true

end

redmine_cua/app/controllers/cua_project_dependencies_controller.rb
class CuaProjectDependenciesController < ApplicationController
  unloadable

  before_filter :find_project_by_project_id, :authorize, :only => [:index]

  def index

    @field = params[:field]

    @order = params[:order]

    if @field.nil?
      @field = "project_id"
    end

    if @order.nil?
      @order = "ASC"
    end

  	@dependencies = CuaDependencies.by_project(@project).order(@field+" "+@order)

  	@states = CuaDependencies.by_project(@project).group(:state).count
  end

  def indexall

    @field = params[:field]

    @order = params[:order]

    if @field.nil?
      @field = "project_id"
    end

    if @order.nil?
      @order = "ASC"
    end
    
  	@dependencies = CuaDependencies.all.order(@field+" "+@order)

  	@states = CuaDependencies.group(:state).count
  end
end

redmine_cua/app/controllers/cua_project_security_issues_controller.rb
class CuaProjectSecurityIssuesController < ApplicationController
  unloadable

  before_filter :find_project_by_project_id, :authorize, :only => [:index]

  def index

    @field = params[:field]

    @order = params[:order]

    if @field.nil?
      @field = "project_id"
    end

    if @order.nil?
      @order = "ASC"
    end

  	@security_issues = CuaSecurityIssues.by_project(@project).order(@field+" "+@order)

  	@states = CuaSecurityIssues.by_project(@project).group(:state).count
  end

  def indexall

    @field = params[:field]

    @order = params[:order]

    if @field.nil?
      @field = "project_id"
    end

    if @order.nil?
      @order = "ASC"
    end
    
  	@security_issues = CuaSecurityIssues.all.order(@field+" "+@order)

  	@states = CuaSecurityIssues.group(:state).count
  end
end

redmine_cua/app/controllers/cua_project_settings_controller.rb
class CuaProjectSettingsController < ApplicationController
  unloadable

  # Redmine ApplicationController method
  before_filter :find_project_by_project_id
  before_filter :load_cua_settings


  def save
    unless params[:cua_setting].nil?
      if @cua_setting.update_attributes(params[:cua_setting])
        flash[:notice] = l(:notice_settings_updated)
      else
        flash[:error] = @cua_setting.errors.full_messages.to_sentence
      end
    end
    redirect_to settings_project_path(@project, 'cua')
  end



  private


    def load_cua_settings
      @cua_setting = @project.cua_setting
    end

end

redmine_cua/app/controllers/cua_settings_controller.rb
class CuaSettingsController < ApplicationController
  unloadable

  # Redmine ApplicationController method
  before_filter :find_project_by_project_id
  before_filter :load_cua_settings


  def save
    unless params[:cua_setting].nil?
      if @cua_setting.update_attributes(params[:cua_setting])
        flash[:notice] = l(:notice_settings_updated)
      else
        flash[:error] = @cua_setting.errors.full_messages.to_sentence
      end
    end
    redirect_to settings_project_path(@project, 'cua')
  end



  private


    def load_cua_settings
      if @project.cua_setting.nil?
        @cua_setting = @project.build_cua_setting
      else
        @cua_setting = @project.cua_setting
      end
      
    end

end

redmine_cua/app/helpers/cua_project_dependencies_helper.rb
module CuaProjectDependenciesHelper
end

redmine_cua/app/views/cua_project_dependencies/index.html.erb
<style type="text/css">
.toremove{
	background-color: red !important;
	color: white !important;
	font-weight: bold;
}
.toupdate{
	background-color: orange !important;
}

</style>

<div class="contextual">

</div>
<h2><%= l(:project_dependencies) %></h2>
<% if @dependencies.any? %>
<div class="autoscroll">
<table class="list">
  <thead><tr>
  <th><%= link_to l(:field_name), {:action => 'index', :field => 'library', :order => ((@field=='library' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_version), {:action => 'index', :field => 'version', :order => ((@field=='version' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_state), {:action => 'index', :field => 'state', :order => ((@field=='state' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_update_to), {:action => 'index', :field => 'to_library', :order => ((@field=='to_library' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_update_to_version), {:action => 'index', :field => 'to_version', :order => ((@field=='to_version' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_last_update), {:action => 'index', :field => 'updated_at', :order => ((@field=='updated_at' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
    <th></th>
  </tr></thead>
  <tbody>
<% for dependency in @dependencies -%>
  <tr class="<%= (dependency.do_remove == true)? "toremove":"" %> <%= (dependency.do_update == true)? "toupdate":"" %> <%= cycle("odd", "even") %>">
  <td class=""><%= dependency.library %></td>
  <td class=""><%= dependency.version %></td>
  <td class=""><%= dependency.state %></td>
  <td class=""><%= dependency.to_library %></td>
  <td class=""><%= dependency.to_version %></td>
  <td class=""><%= format_time(dependency.updated_at) %></td>
    <td class="buttons">&nbsp;
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% content_for :sidebar do %>
<h3><%= l(:state_count) %></h3>
<% if @states.any? %>
<div class="">
<table class="list">
  <thead><tr>
  <th><%= l(:field_state) %></th>
  <th><%= l(:field_count) %></th>
  </tr></thead>
  <tbody>
<% for state in @states -%>
  <tr class="<%= cycle("odd", "even") %>">
  <td class=""><%= l(state[0]) %></td>
  <td class=""><%= state[1] %></td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
<% end %>

redmine_cua/app/views/cua_project_dependencies/indexall.html.erb
<style type="text/css">
.toremove{
	background-color: red !important;
	color: white !important;
	font-weight: bold;
}
.toupdate{
	background-color: orange !important;
}

</style>

<div class="contextual">

</div>
<h2><%= l(:all_dependencies) %></h2>
<% if @dependencies.any? %>
<div class="autoscroll">
<table class="list">
  <thead><tr>
  <th><%= link_to l(:field_project), {:action => 'indexall', :field => 'project_id', :order => ((@field=='project_id' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_name), {:action => 'indexall', :field => 'library', :order => ((@field=='library' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_version), {:action => 'indexall', :field => 'version', :order => ((@field=='version' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_state), {:action => 'indexall', :field => 'state', :order => ((@field=='state' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_update_to), {:action => 'indexall', :field => 'to_library', :order => ((@field=='to_library' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_update_to_version), {:action => 'indexall', :field => 'to_version', :order => ((@field=='to_version' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_last_update), {:action => 'indexall', :field => 'updated_at', :order => ((@field=='updated_at' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
    <th></th>
    <th></th>
  </tr></thead>
  <tbody>
<% for dependency in @dependencies -%>
  <tr class="<%= (dependency.do_remove == true)? "toremove":"" %> <%= (dependency.do_update == true)? "toupdate":"" %> <%= cycle("odd", "even") %>">
  <td class=""><% if dependency.project == nil then %>-<% else %><%= link_to dependency.project.name, {:controller => 'cua_project_dependencies', :action=> 'index', :project_id => dependency.project} %><% end %></td>
  <td class=""><%= dependency.library %></td>
  <td class=""><%= dependency.version %></td>
  <td class=""><%= dependency.state %></td>
  <td class=""><%= dependency.to_library %></td>
  <td class=""><%= dependency.to_version %></td>
  <td class=""><%= format_time(dependency.updated_at) %></td>
    <td class="buttons">&nbsp;
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% content_for :sidebar do %>
<h3><%= l(:state_count) %></h3>
<% if @states.any? %>
<div class="">
<table class="list">
  <thead><tr>
  <th><%= l(:field_state) %></th>
  <th><%= l(:field_count) %></th>
  </tr></thead>
  <tbody>
<% for state in @states -%>
  <tr class="<%= cycle("odd", "even") %>">
  <td class=""><%= l(state[0]) %></td>
  <td class=""><%= state[1] %></td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
<% end %>

redmine_cua/app/views/cua_project_security_issues/index.html.erb
<style type="text/css">
.toremove{
	background-color: red !important;
	color: white !important;
	font-weight: bold;
}
.toupdate{
	background-color: orange !important;
}

</style>

<div class="contextual">

</div>
<h2><%= l(:project_security_issues) %></h2>
<% if @security_issues.any? %>
<div class="autoscroll">
<table class="list">
  <thead><tr>
  <th><%= link_to l(:field_name), {:action => 'index', :field => 'library', :order => ((@field=='library' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_version), {:action => 'index', :field => 'version', :order => ((@field=='version' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_state), {:action => 'index', :field => 'state', :order => ((@field=='state' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_last_update), {:action => 'index', :field => 'updated_at', :order => ((@field=='updated_at' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
    <th></th>
  </tr></thead>
  <tbody>
<% for security_issue in @security_issues -%>
  <tr class="<%= (security_issue.do_secure == true)? "toremove":"" %> <%= cycle("odd", "even") %>">
  <td class=""><%= security_issue.library %></td>
  <td class=""><%= security_issue.version %></td>
  <td class=""><%= security_issue.state %></td>
  <td class=""><%= format_time(security_issue.updated_at) %></td>
    <td class="buttons">&nbsp;
    </td>
  </tr>
  <tr>
    <td colspan="5" style="text-align: left;">
      <%
        details = ActiveSupport::JSON.decode(security_issue.details)
        details.each do | l1, cve | -%>
          <a href="<%= cve["link"] %>" target="_cve"><%= cve["title"] %></a><br>
        <% end
      -%>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% content_for :sidebar do %>
<h3><%= l(:state_count) %></h3>
<% if @states.any? %>
<div class="">
<table class="list">
  <thead><tr>
  <th><%= l(:field_state) %></th>
  <th><%= l(:field_count) %></th>
  </tr></thead>
  <tbody>
<% for state in @states -%>
  <tr class="<%= cycle("odd", "even") %>">
  <td class=""><%= l(state[0]) %></td>
  <td class=""><%= state[1] %></td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
<% end %>

redmine_cua/app/views/cua_project_security_issues/indexall.html.erb
<style type="text/css">
.toremove{
	background-color: red !important;
	color: white !important;
	font-weight: bold;
}
.toupdate{
	background-color: orange !important;
}

</style>

<div class="contextual">

</div>
<h2><%= l(:all_security_issues) %></h2>
<% if @security_issues.any? %>
<div class="autoscroll">
<table class="list">
  <thead><tr>
  <th><%= link_to l(:field_project), {:action => 'indexall', :field => 'project_id', :order => ((@field=='project_id' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_name), {:action => 'indexall', :field => 'library', :order => ((@field=='library' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_version), {:action => 'indexall', :field => 'version', :order => ((@field=='version' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_state), {:action => 'indexall', :field => 'state', :order => ((@field=='state' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
  <th><%= link_to l(:field_last_update), {:action => 'indexall', :field => 'updated_at', :order => ((@field=='updated_at' && @order=='ASC')? 'DESC' : 'ASC')} %></th>
    <th></th>
    <th></th>
  </tr></thead>
  <tbody>
<% for security_issue in @security_issues -%>
  <tr class="<%= (security_issue.do_secure == true)? "toremove":"" %> <%= cycle("odd", "even") %>">
  <td class=""><% if security_issue.project == nil then %>-<% else %><%= link_to security_issue.project.name, {:controller => 'cua_project_security_issues', :action=> 'index', :project_id => security_issue.project} %><% end %></td>
  <td class=""><%= security_issue.library %></td>
  <td class=""><%= security_issue.version %></td>
  <td class=""><%= security_issue.state %></td>
  <td class=""><%= format_time(security_issue.updated_at) %></td>
    <td class="buttons">&nbsp;
    </td>
  </tr>
  <tr>
    <td colspan="5" style="text-align: left;">
      <%
        details = ActiveSupport::JSON.decode(security_issue.details)
        details.each do | l1, cve | -%>
          <a href="<%= cve["link"] %>" target="_cve"><%= cve["title"] %></a><br>
        <% end
      -%>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% content_for :sidebar do %>
<h3><%= l(:state_count) %></h3>
<% if @states.any? %>
<div class="">
<table class="list">
  <thead><tr>
  <th><%= l(:field_state) %></th>
  <th><%= l(:field_count) %></th>
  </tr></thead>
  <tbody>
<% for state in @states -%>
  <tr class="<%= cycle("odd", "even") %>">
  <td class=""><%= l(state[0]) %></td>
  <td class=""><%= state[1] %></td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
<% end %>

redmine_cua/app/views/projects/settings/_redmine_cua.html.erb
<%= error_messages_for 'cua_setting' %>


<%= form_for @cua_setting, url:  cua_settings_save_path(@project),
                             html: { method: :put } do |f| %>
  <div class="box tabular">
    <p>
      <label><%= l(:label_cua_lock_path)%></label>
      <%= f.text_field :lock_path, size: 50 %>
      <br>
      <em><%= l(:label_cua_lock_path_desc)%></em>
    </p>
    <p>
      <label><%= l(:label_cua_php_bin)%></label>
      <%= f.text_field :php_bin, size: 50 %>
      <br>
      <em><%= l(:label_cua_php_bin_desc)%></em>
    </p>
    <p>
      <label><%= l(:label_cua_check_update)%></label>
      <%= f.check_box :check_update, {}, 'true' %>
    </p>
    <p>
      <label><%= l(:label_cua_check_security)%></label>
      <%= f.check_box :check_security, {}, 'true' %>
    </p>
  </div>
  <%= submit_tag l(:button_save) %> 
<% end %>